# Generated by Django 4.0.2 on 2022-07-03 08:57

from django.db import migrations
from django.contrib.auth.models import User


def change_username(apps, schema_editor):
    # User = apps.get_model('User')
    Profile = apps.get_model('accounts', 'Profile')
    
    for profile in Profile.objects.all():
        user = User.objects.get(id=profile.user.id)
        user.username = profile.mobile
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(change_username),
    ]
