# Generated by Django 4.0.2 on 2022-06-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_pricehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsoul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
