# Generated by Django 4.0.2 on 2022-06-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_mahsoul'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsoul',
            name='old_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mahsoul',
            name='price',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
