# Generated by Django 4.0.2 on 2022-07-03 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_mahsoul_old_price_mahsoul_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='PriceHistory',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
